name: Puppet Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  spec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        puppet: ['7', '8']
    name: Puppet ${{ matrix.puppet }}
    container:
      image: ghcr.io/voxpupuli/voxbox:${{ matrix.puppet }}
    steps:
      - uses: actions/checkout@v4

      - name: Run spec tests
        run: rake spec

  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/voxpupuli/voxbox:8
    steps:
      - uses: actions/checkout@v4

      - name: Run puppet-lint
        run: rake lint

  syntax:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/voxpupuli/voxbox:8
    steps:
      - uses: actions/checkout@v4

      - name: Validate syntax
        run: rake validate
